### ISSUE TITLE
support of generic font families

### ISSUE THREAD

**Issue by wwachsmann** [bramstein/fontfaceobserver#9]
Hi,

is there a support planed for generic font families? Actually, if i try to validate one of the generic font families (e.g. "Tahoma") the promise fails. Supporting generic font families would be really awesome. Please let me know, if this feature isn't planed or even useful for your library.

Thanks a lot - at least for this beautiful library, you did a nice work! ;-)

**Comment by bramstein** [comment]
Thanks for the report! I had a look and I think this is a bug. Due to a funny coincidence the width of the default serif font on OS X is the same the width of Tahoma for the default test string. This causes it to ignore the change in width (because it is essentially the same). I'll believe this can be fixed, so I'll look into it when I have some more time.

**Comment by bramstein** [comment]
I think I fixed this bug in v1.4.3. Could you try upgrading and see if that fixes the problem?

**Comment by wwachsmann** [comment]
Thanks for the upgrade. I'm sorry to let you know that your fix doesn't solve the problem. I tried it again with Tahoma, Tahoma serif and Tahoma sans-serif and at least with Arial, Arial serif and Arial sans-serif. The observer couldn't load any of these fonts. Other generic font families like Verdana or Georgia are working fine. Tested on OS X with Chrome 41.0.2272.89 (64-bit)

**Comment by bramstein** [comment]
Thanks for getting back to me. Hm, do you have some example code? I added a test case that covers Tahoma and that passes on Chrome 41 on OS X.

**Comment by bramstein** [comment]
I'm closing this issue because it has been inactive for a while and the issue appears fixed. If you still have the same problem with the latest version of FontFaceObserver, please feel free to reopen this issue.
